---
- name: configure kvm hosts 
  hosts: all
  tasks:
    - name: List vms
      community.libvirt.virt: 
        command: list_vms
      register: vms

    - name: Print Vms
      debug: 
        msg: "{{ vms }}"
